# Site settings
title: My Projects
description: On this page I'll present some of my previous projects.
keywords: Projects, G710, Awesome
author: G710
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
